spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        hdm2ddl: update
        show_sql: true
        format_sql: true
        use_sql_comments: true
  devtools:
    livereload:
      enabled: true
  flyway:
    url: jdbc:mysql://localhost:3306/bewithme
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/bewithme?serverTimezone=Asia/Seoul&useSSL=true&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#---
#logging:
#  config: classpath:log4j2.yml