spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  devtools:
    livereload:
      enabled: true
  flyway:
    locations: classpath:/db/migration
    sql-migration-suffixes: ddl
    baseline-on-migrate: true
    enabled: true
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/bewithme?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
#---
#logging:
#  config: classpath:log4j2.yml