spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  devtools:
    livereload:
      enabled: true
  flyway:
    enabled: true
    encoding: UTF-8
  data:
    maria:
      jdbc-url: jdbc:mariadb://localhost:3307/ourkitchen
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: ok1234
---
logging:
  config: classpath:log4j2.yml